---
title: 延迟调用（defer）
date: 2023-05-06 15:41:45
permalink: /pages/96571a/
categories:
  - 服务端
  - Go
tags:
  - defer
author: 
  name: coding-linheng
  link: https://github.com/coding-linheng
---

## defer特性：
```text
1. 关键字 defer 用于注册延迟调用。
2. 这些调用直到 return 前才被执。因此，可以用来做资源清理。
3. 多个defer语句，按先进后出的方式执行。
4. defer语句中的变量，在defer声明时就决定了。
5. defer 是先进后出
```


## defer闭包：
```go
package main

import "fmt"

func main() {
    var whatever [5]struct{}
    for i := range whatever {
        defer func() { fmt.Println(i) }()
    }
}

//output:
4 4 4 4 4  
```
由于闭包用到的变量 i 在执行的时候已经变成4,所以输出全都是4.
defer后面的语句在执行的时候，函数调用的参数会被保存起来，但是不执行。也就是复制了一份。但是并没有说struct这里的this指针如何处理，通过这个例子可以看出go语言并没有把这个明确写出来的this指针当作参数来看待。

```go
package main

import (
	"errors"
	"fmt"
)

func foo(a, b int) (i int, err error) {
	defer fmt.Printf("first defer err %v\n", err)
	defer func(err error) { fmt.Printf("second defer err %v\n", err) }(err)
	defer func() { fmt.Printf("third defer err %v\n", err) }()
	if b == 0 {
		err = errors.New("divided by zero")
		return
	}

	i = a / b
	return
}

func main() {
	foo(2, 0)
}

//output
third defer err divided by zero!
    second defer err <nil>
    first defer err <nil>
```
第一 第二个defer的err都是nil，因为这两个defer的err是在defer语句声明的时候就已经确定了，而第三个defer的err是在执行的时候才确定的，所以是divided by zero。
如果 defer 后面跟的不是一个 closure 最后执行的时候我们得到的并不是最新的值。

```go
package main

import (
	"errors"
	"fmt"
)

func foo(a, b int) (i int, err error) {
    err = errors.New("divided by zero111")
	defer fmt.Printf("first defer err %v\n", err)
	defer func(err error) { fmt.Printf("second defer err %v\n", err) }(err)
	defer func() { fmt.Printf("third defer err %v\n", err) }()
	if b == 0 {
		err = errors.New("divided by zero")
		return
	}

	i = a / b
	return
}

func main() {
	foo(2, 0)
}

//output
third defer err divided by zero
second defer err divided by zero11
first defer err divided by zero11
```





